name: deep-learning-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - tensorflow
  - pip
  - pip:
      - nbgitpuller
      - sphinx-gallery

