name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - obspy
  - numpy
  - pip
  - pip:
    - nbgitpuller
    - tensorflow
    - pandas
    - matplotlib
    - seaborn
    - scikit-learn
